name: Build Pufferfish linear
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Pufferfish
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: build/libs/paper-*.jar
