name: Build Pufferfish linear
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Pufferfish
        run: ./gradlew build
      - name: check build folder
        run: la & cd build/libs & ll
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: build/libs/*.jar
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_number }}
          release_name: Pufferfish linear v${{ github.run_number }}
          body: This is the release for Pufferfish linear v${{ github.run_number }}.
      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          asset_path: build/libs/paper-*.jar
          asset_name: paper-v${{ github.run_number }}.jar
          release_id: ${{ steps.create-release.outputs.id }}
