name: Build Pufferfish linear
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: mf entering informations
        run: git config --global user.email khangrydev@gmail.com && git config --global user.name Khangry
      - name: Apply patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: create a paperclipjar
        run: ./gradlew paperclip --no-daemon --stacktrace
      - name: artifact xd
        uses: actions/upload-artifact@v2
        with:
          name: AlynaaMC 1.18
          path: build/libs/*.jar
