name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: My App
        path: build/libs/*.jar
